# vim: set ts=2 sts=2 sw=2 expandtab:
version: '2'

services:
  mesos-slave:
    image: runner-mesos
    privileged: true
    environment:
      MESOS_MASTER: zk://zookeeper:2181/mesos
      MESOS_CONTAINERIZERS: mesos
      MESOS_WORK_DIR: /var/tmp/mesos
      MESOS_LOG_DIR: /var/log/mesos
      MESOS_ISOLATION: filesystem/linux,docker/runtime
      MESOS_EXEC_DIR: /src/mesos/src/
      MESOS_HOSTNAME: localhost
    volumes:
      - ../../criteo_mesos:/src/mesos/
